import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { randomUUID } from 'node:crypto';
import { CompleteMultipartUploadCommand, CreateMultipartUploadCommand, AbortMultipartUploadCommand, S3Client, UploadPartCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { prisma } from '../server.js';
import { requireAuth, userId, requireMembership } from '../auth.js';
import { entitlementFor } from './subscriptions.js';

const s3 = new S3Client({ region: process.env.S3_REGION ?? 'auto', endpoint: process.env.S3_ENDPOINT || undefined, forcePathStyle: process.env.S3_FORCE_PATH_STYLE === 'true', credentials: process.env.S3_ACCESS_KEY_ID ? { accessKeyId: process.env.S3_ACCESS_KEY_ID, secretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? '' } : undefined });
const bucket = process.env.S3_BUCKET ?? 'chisme-encrypted';
const partSize = 64 * 1024 * 1024;
function publicUpload(x: { id: string; objectKey: string; sizeBytes: bigint; parts: number; status: string }) { return { ...x, sizeBytes: x.sizeBytes.toString() }; }
export async function uploadRoutes(app: FastifyInstance) {
  app.addHook('preHandler', requireAuth);
  app.post('/multipart', async (request, reply) => { const input = z.object({ conversationId: z.string(), filename: z.string().min(1).max(255), contentType: z.string().max(200), sizeBytes: z.coerce.bigint().positive(), sha256: z.string().regex(/^[a-f0-9]{64}$/).optional() }).parse(request.body); const uid = userId(request); if (!await requireMembership(input.conversationId, uid)) return reply.code(403).send({ error: 'not_a_member' }); const plan = await entitlementFor(uid); if (input.sizeBytes > plan.maxFileBytes) return reply.code(413).send({ error: 'file_too_large', maxFileBytes: plan.maxFileBytes.toString() }); const key = `encrypted/${uid}/${randomUUID()}`; const created = await s3.send(new CreateMultipartUploadCommand({ Bucket: bucket, Key: key, ContentType: 'application/octet-stream', Metadata: { encrypted: 'true', original_name: input.filename } })); const upload = await prisma.fileUpload.create({ data: { uploaderId: uid, conversationId: input.conversationId, objectKey: key, multipartId: created.UploadId, filename: input.filename, contentType: input.contentType, sizeBytes: input.sizeBytes, sha256: input.sha256, expiresAt: new Date(Date.now() + 24 * 3600000) } }); return reply.code(201).send({ upload: publicUpload(upload), partSize, partCount: Math.ceil(Number(input.sizeBytes) / partSize), encrypted: true }); });
  app.post('/:id/part-url', async (request, reply) => { const { id } = z.object({ id: z.string() }).parse(request.params); const input = z.object({ partNumber: z.coerce.number().int().min(1).max(10_000) }).parse(request.body); const upload = await prisma.fileUpload.findFirst({ where: { id, uploaderId: userId(request), status: 'INITIATED' } }); if (!upload?.multipartId || upload.expiresAt < new Date()) return reply.code(404).send({ error: 'upload_not_found_or_expired' }); const url = await getSignedUrl(s3, new UploadPartCommand({ Bucket: bucket, Key: upload.objectKey, UploadId: upload.multipartId, PartNumber: input.partNumber }), { expiresIn: 900 }); return { url, expiresIn: 900, partNumber: input.partNumber }; });
  app.post('/:id/complete', async (request, reply) => { const { id } = z.object({ id: z.string() }).parse(request.params); const input = z.object({ parts: z.array(z.object({ ETag: z.string(), PartNumber: z.number().int().min(1) })).min(1).max(10_000) }).parse(request.body); const upload = await prisma.fileUpload.findFirst({ where: { id, uploaderId: userId(request), status: 'INITIATED' } }); if (!upload?.multipartId) return reply.code(404).send({ error: 'upload_not_found' }); await s3.send(new CompleteMultipartUploadCommand({ Bucket: bucket, Key: upload.objectKey, UploadId: upload.multipartId, MultipartUpload: { Parts: input.parts.sort((a, b) => a.PartNumber - b.PartNumber) } })); const updated = await prisma.fileUpload.update({ where: { id }, data: { status: 'COMPLETED', parts: input.parts.length, completedAt: new Date() } }); return publicUpload(updated); });
  app.delete('/:id', async (request, reply) => { const { id } = z.object({ id: z.string() }).parse(request.params); const upload = await prisma.fileUpload.findFirst({ where: { id, uploaderId: userId(request), status: 'INITIATED' } }); if (!upload) return reply.code(404).send({ error: 'upload_not_found' }); if (upload.multipartId) await s3.send(new AbortMultipartUploadCommand({ Bucket: bucket, Key: upload.objectKey, UploadId: upload.multipartId })); await prisma.fileUpload.update({ where: { id }, data: { status: 'ABORTED' } }); return { ok: true }; });
}
